import {Promise} from "es6-promise";
import {
    ContextInfo,
    List,
    Types
} from "gd-sprest";

/**
 * The interface for the data.
 */
export interface IData {
    City: string;
    County: string;
    State: string;
}

/**
 * Data Source
 */
export class Data {
    /**
     * Properties
     */
    private static get IsSPOnline(): boolean { return ContextInfo.existsFl; }

    // Method to get the data
    static get(): PromiseLike<IData[]> {
        // Return a promise
        return new Promise((resolve, reject) => {
            // See if the $REST library exists
            if (this.IsSPOnline) {
                // Get the list
                (new List("Locations"))
                    // Get the items
                    .Items()
                    // Query the data
                    .query({
                        OrderBy: ["State", "County", "Title"]
                    })
                    // Execute the request
                    .execute((items) => {
                        let data: IData[] = [];

                        // Parse the items
                        for (let item of items.results) {
                            // Add the item to the data array
                            data.push({
                                City: item["Title"],
                                County: item["County"],
                                State: item["State"]
                            });
                        }

                        // Resolve the request
                        resolve(data);
                    });
            } else {
                // Resolve the request with test data
                resolve(TestData);
            }
        });
    }
}

/**
 * Test Data
 */
const TestData:IData[] = [
    { City: "Anchorage", County: "Anchorage", State: "AK" },
    { City: "Fairbanks", County: "Fairbanks North Star", State: "AK" },
    { City: "Little Rock", County: "Pulaski", State: "AR" },
    { City: "Mesa", County: "Maricopa", State: "AZ" },
    { City: "Peoria", County: "Maricopa", State: "AZ" },
    { City: "Phoenix", County: "Maricopa", State: "AZ" },
    { City: "Scottsdale", County: "Maricopa", State: "AZ" },
    { City: "Berkeley", County: "Alameda", State: "CA" },
    { City: "Hayward", County: "Alameda", State: "CA" },
    { City: "Oakland", County: "Alameda", State: "CA" },
    { City: "San Leandro", County: "Alameda", State: "CA" },
    { City: "Oroville", County: "Butte", State: "CA" },
    { City: "Concord", County: "Contra Costa", State: "CA" },
    { City: "Oakley", County: "Contra Costa", State: "CA" },
    { City: "San Ramon", County: "Contra Costa", State: "CA" },
    { City: "Bellflower", County: "Los Angeles", State: "CA" },
    { City: "Beverly Hills", County: "Los Angeles", State: "CA" },
    { City: "El Monte", County: "Los Angeles", State: "CA" },
    { City: "Gardena", County: "Los Angeles", State: "CA" },
    { City: "Los Angeles", County: "Los Angeles", State: "CA" },
    { City: "Northridge", County: "Los Angeles", State: "CA" },
    { City: "Pasadena", County: "Los Angeles", State: "CA" },
    { City: "Pomona", County: "Los Angeles", State: "CA" },
    { City: "San Gabriel", County: "Los Angeles", State: "CA" },
    { City: "Van Nuys", County: "Los Angeles", State: "CA" },
    { City: "Novato", County: "Marin", State: "CA" },
    { City: "Anaheim", County: "Orange", State: "CA" },
    { City: "Costa Mesa", County: "Orange", State: "CA" },
    { City: "Huntington Beach", County: "Orange", State: "CA" },
    { City: "Santa Ana", County: "Orange", State: "CA" },
    { City: "Roseville", County: "Placer", State: "CA" },
    { City: "Cathedral City", County: "Riverside", State: "CA" },
    { City: "Riverside", County: "Riverside", State: "CA" },
    { City: "Thousand Palms", County: "Riverside", State: "CA" },
    { City: "Sacramento", County: "Sacramento", State: "CA" },
    { City: "Ontario", County: "San Bernardino", State: "CA" },
    { City: "San Bernardino", County: "San Bernardino", State: "CA" },
    { City: "El Cajon", County: "San Diego", State: "CA" },
    { City: "Escondido", County: "San Diego", State: "CA" },
    { City: "La Mesa", County: "San Diego", State: "CA" },
    { City: "San Diego", County: "San Diego", State: "CA" },
    { City: "San Francisco", County: "San Francisco", State: "CA" },
    { City: "Stockton", County: "San Joaquin", State: "CA" },
    { City: "Burlingame", County: "San Mateo", State: "CA" },
    { City: "Pacifica", County: "San Mateo", State: "CA" },
    { City: "San Carlos", County: "San Mateo", State: "CA" },
    { City: "San Mateo", County: "San Mateo", State: "CA" },
    { City: "South San Francisco", County: "San Mateo", State: "CA" },
    { City: "San Jose", County: "Santa Clara", State: "CA" },
    { City: "Santa Clara", County: "Santa Clara", State: "CA" },
    { City: "Saratoga", County: "Santa Clara", State: "CA" },
    { City: "Rohnert Park", County: "Sonoma", State: "CA" },
    { City: "Santa Rosa", County: "Sonoma", State: "CA" },
    { City: "Camarillo", County: "Ventura", State: "CA" },
    { City: "Thousand Oaks", County: "Ventura", State: "CA" },
    { City: "Englewood", County: "Arapahoe", State: "CO" },
    { City: "Boulder", County: "Boulder", State: "CO" },
    { City: "Denver", County: "Denver", State: "CO" },
    { City: "Littleton", County: "Douglas", State: "CO" },
    { City: "Colorado Springs", County: "El Paso", State: "CO" },
    { City: "Bridgeport", County: "Fairfield", State: "CT" },
    { City: "Norwalk", County: "Fairfield", State: "CT" },
    { City: "New Haven", County: "New Haven", State: "CT" },
    { City: "North Haven", County: "New Haven", State: "CT" },
    { City: "Washington", County: "District of Columbia", State: "DC" },
    { City: "Cocoa", County: "Brevard", State: "FL" },
    { City: "Satellite Beach", County: "Brevard", State: "FL" },
    { City: "Crystal River", County: "Citrus", State: "FL" },
    { City: "Homosassa", County: "Citrus", State: "FL" },
    { City: "Jacksonville", County: "Duval", State: "FL" },
    { City: "Brandon", County: "Hillsborough", State: "FL" },
    { City: "Tampa", County: "Hillsborough", State: "FL" },
    { City: "Hialeah", County: "Miami-Dade", State: "FL" },
    { City: "Homestead", County: "Miami-Dade", State: "FL" },
    { City: "Miami", County: "Miami-Dade", State: "FL" },
    { City: "Opa Locka", County: "Miami-Dade", State: "FL" },
    { City: "Crestview", County: "Okaloosa", State: "FL" },
    { City: "Orlando", County: "Orange", State: "FL" },
    { City: "Lake Worth", County: "Palm Beach", State: "FL" },
    { City: "Longwood", County: "Seminole", State: "FL" },
    { City: "Daytona Beach", County: "Volusia", State: "FL" },
    { City: "Oak Hill", County: "Volusia", State: "FL" },
    { City: "Trion", County: "Chattooga", State: "GA" },
    { City: "Atlanta", County: "Dekalb", State: "GA" },
    { City: "Albany", County: "Dougherty", State: "GA" },
    { City: "Douglasville", County: "Douglas", State: "GA" },
    { City: "Atlanta", County: "Fulton", State: "GA" },
    { City: "Hilo", County: "Hawaii", State: "HI" },
    { City: "Honolulu", County: "Honolulu", State: "HI" },
    { City: "Pearl City", County: "Honolulu", State: "HI" },
    { City: "Des Moines", County: "Polk", State: "IA" },
    { City: "Boise", County: "Ada", State: "ID" },
    { City: "Moscow", County: "Latah", State: "ID" },
    { City: "Arlington Heights", County: "Cook", State: "IL" },
    { City: "Chicago", County: "Cook", State: "IL" },
    { City: "Elk Grove Village", County: "Cook", State: "IL" },
    { City: "Evanston", County: "Cook", State: "IL" },
    { City: "Palatine", County: "Cook", State: "IL" },
    { City: "Rolling Meadows", County: "Cook", State: "IL" },
    { City: "Wheeling", County: "Cook", State: "IL" },
    { City: "Highland Park", County: "Lake", State: "IL" },
    { City: "Rockford", County: "Winnebago", State: "IL" },
    { City: "Fort Wayne", County: "Allen", State: "IN" },
    { City: "Elkhart", County: "Elkhart", State: "IN" },
    { City: "Fortville", County: "Hancock", State: "IN" },
    { City: "Indianapolis", County: "Marion", State: "IN" },
    { City: "Bloomington", County: "Monroe", State: "IN" },
    { City: "South Bend", County: "St Joseph", State: "IN" },
    { City: "Abilene", County: "Dickinson", State: "KS" },
    { City: "Hays", County: "Ellis", State: "KS" },
    { City: "Overland Park", County: "Johnson", State: "KS" },
    { City: "Shawnee", County: "Johnson", State: "KS" },
    { City: "Burlington", County: "Boone", State: "KY" },
    { City: "Metairie", County: "Jefferson", State: "LA" },
    { City: "Broussard", County: "Lafayette", State: "LA" },
    { City: "Lafayette", County: "Lafayette", State: "LA" },
    { City: "New Orleans", County: "Orleans", State: "LA" },
    { City: "Houma", County: "Terrebonne", State: "LA" },
    { City: "New Bedford", County: "Bristol", State: "MA" },
    { City: "North Attleboro", County: "Bristol", State: "MA" },
    { City: "Cambridge", County: "Middlesex", State: "MA" },
    { City: "Concord", County: "Middlesex", State: "MA" },
    { City: "Wilmington", County: "Middlesex", State: "MA" },
    { City: "Middleboro", County: "Plymouth", State: "MA" },
    { City: "Boston", County: "Suffolk", State: "MA" },
    { City: "Westborough", County: "Worcester", State: "MA" },
    { City: "Worcester", County: "Worcester", State: "MA" },
    { City: "Glen Burnie", County: "Anne Arundel", State: "MD" },
    { City: "Hanover", County: "Anne Arundel", State: "MD" },
    { City: "Owings Mills", County: "Baltimore", State: "MD" },
    { City: "Parkville", County: "Baltimore", State: "MD" },
    { City: "Baltimore", County: "Baltimore City", State: "MD" },
    { City: "Preston", County: "Caroline", State: "MD" },
    { City: "Hampstead", County: "Carroll", State: "MD" },
    { City: "Aberdeen", County: "Harford", State: "MD" },
    { City: "Bladensburg", County: "Prince Georges", State: "MD" },
    { City: "Clinton", County: "Prince Georges", State: "MD" },
    { City: "Hyattsville", County: "Prince Georges", State: "MD" },
    { City: "Easton", County: "Talbot", State: "MD" },
    { City: "Salisbury", County: "Wicomico", State: "MD" },
    { City: "Warren", County: "Knox", State: "ME" },
    { City: "Bangor", County: "Penobscot", State: "ME" },
    { City: "Niles", County: "Berrien", State: "MI" },
    { City: "East Lansing", County: "Ingham", State: "MI" },
    { City: "Lansing", County: "Ingham", State: "MI" },
    { City: "Grand Rapids", County: "Kent", State: "MI" },
    { City: "Brighton", County: "Livingston", State: "MI" },
    { City: "Sterling Heights", County: "Macomb", State: "MI" },
    { City: "Milan", County: "Monroe", State: "MI" },
    { City: "Muskegon", County: "Muskegon", State: "MI" },
    { City: "Rochester", County: "Oakland", State: "MI" },
    { City: "Southfield", County: "Oakland", State: "MI" },
    { City: "Waterford", County: "Oakland", State: "MI" },
    { City: "Ann Arbor", County: "Washtenaw", State: "MI" },
    { City: "Dearborn", County: "Wayne", State: "MI" },
    { City: "Taylor", County: "Wayne", State: "MI" },
    { City: "Burnsville", County: "Dakota", State: "MN" },
    { City: "Hopkins", County: "Hennepin", State: "MN" },
    { City: "Minneapolis", County: "Hennepin", State: "MN" },
    { City: "Saint Paul", County: "Ramsey", State: "MN" },
    { City: "Northfield", County: "Rice", State: "MN" },
    { City: "Shakopee", County: "Scott", State: "MN" },
    { City: "Saint Joseph", County: "Buchanan", State: "MO" },
    { City: "Valley Park", County: "Saint Louis", State: "MO" },
    { City: "Saint Louis", County: "Saint Louis City", State: "MO" },
    { City: "Biloxi", County: "Harrison", State: "MS" },
    { City: "Jackson", County: "Hinds", State: "MS" },
    { City: "Meridian", County: "Lauderdale", State: "MS" },
    { City: "Pearl", County: "Rankin", State: "MS" },
    { City: "Butte", County: "Silver Bow", State: "MT" },
    { City: "Burlington", County: "Alamance", State: "NC" },
    { City: "Fayetteville", County: "Cumberland", State: "NC" },
    { City: "Greensboro", County: "Guilford", State: "NC" },
    { City: "High Point", County: "Guilford", State: "NC" },
    { City: "Smithfield", County: "Johnston", State: "NC" },
    { City: "Chapel Hill", County: "Orange", State: "NC" },
    { City: "Raleigh", County: "Wake", State: "NC" },
    { City: "Fargo", County: "Cass", State: "ND" },
    { City: "Alliance", County: "Box Butte", State: "NE" },
    { City: "Omaha", County: "Douglas", State: "NE" },
    { City: "Plaistow", County: "Rockingham", State: "NH" },
    { City: "Absecon", County: "Atlantic", State: "NJ" },
    { City: "Atlantic City", County: "Atlantic", State: "NJ" },
    { City: "Margate City", County: "Atlantic", State: "NJ" },
    { City: "Englewood", County: "Bergen", State: "NJ" },
    { City: "Hackensack", County: "Bergen", State: "NJ" },
    { City: "Lyndhurst", County: "Bergen", State: "NJ" },
    { City: "Paramus", County: "Bergen", State: "NJ" },
    { City: "Ramsey", County: "Bergen", State: "NJ" },
    { City: "Ridgefield Park", County: "Bergen", State: "NJ" },
    { City: "Riverton", County: "Burlington", State: "NJ" },
    { City: "Cherry Hill", County: "Camden", State: "NJ" },
    { City: "Bloomfield", County: "Essex", State: "NJ" },
    { City: "Cedar Grove", County: "Essex", State: "NJ" },
    { City: "Fairfield", County: "Essex", State: "NJ" },
    { City: "Livingston", County: "Essex", State: "NJ" },
    { City: "Newark", County: "Essex", State: "NJ" },
    { City: "Nutley", County: "Essex", State: "NJ" },
    { City: "Orange", County: "Essex", State: "NJ" },
    { City: "Bridgeport", County: "Gloucester", State: "NJ" },
    { City: "Harrison", County: "Hudson", State: "NJ" },
    { City: "Jersey City", County: "Hudson", State: "NJ" },
    { City: "Kearny", County: "Hudson", State: "NJ" },
    { City: "Union City", County: "Hudson", State: "NJ" },
    { City: "Flemington", County: "Hunterdon", State: "NJ" },
    { City: "Pittstown", County: "Hunterdon", State: "NJ" },
    { City: "Trenton", County: "Mercer", State: "NJ" },
    { City: "Dunellen", County: "Middlesex", State: "NJ" },
    { City: "Middlesex", County: "Middlesex", State: "NJ" },
    { City: "Monroe Township", County: "Middlesex", State: "NJ" },
    { City: "Freehold", County: "Monmouth", State: "NJ" },
    { City: "Denville", County: "Morris", State: "NJ" },
    { City: "Randolph", County: "Morris", State: "NJ" },
    { City: "Rockaway", County: "Morris", State: "NJ" },
    { City: "Whippany", County: "Morris", State: "NJ" },
    { City: "Toms River", County: "Ocean", State: "NJ" },
    { City: "Clifton", County: "Passaic", State: "NJ" },
    { City: "Little Falls", County: "Passaic", State: "NJ" },
    { City: "Passaic", County: "Passaic", State: "NJ" },
    { City: "Paterson", County: "Passaic", State: "NJ" },
    { City: "Bridgewater", County: "Somerset", State: "NJ" },
    { City: "Somerset", County: "Somerset", State: "NJ" },
    { City: "Somerville", County: "Somerset", State: "NJ" },
    { City: "Plainfield", County: "Union", State: "NJ" },
    { City: "Clovis", County: "Curry", State: "NM" },
    { City: "Las Cruces", County: "Dona Ana", State: "NM" },
    { City: "Carson City", County: "Carson City", State: "NV" },
    { City: "Reno", County: "Washoe", State: "NV" },
    { City: "Albany", County: "Albany", State: "NY" },
    { City: "Wellsville", County: "Allegany", State: "NY" },
    { City: "Bronx", County: "Bronx", State: "NY" },
    { City: "Vestal", County: "Broome", State: "NY" },
    { City: "Buffalo", County: "Erie", State: "NY" },
    { City: "Brooklyn", County: "Kings", State: "NY" },
    { City: "Garden City", County: "Nassau", State: "NY" },
    { City: "Hicksville", County: "Nassau", State: "NY" },
    { City: "Lynbrook", County: "Nassau", State: "NY" },
    { City: "Massapequa", County: "Nassau", State: "NY" },
    { City: "Syosset", County: "Nassau", State: "NY" },
    { City: "Westbury", County: "Nassau", State: "NY" },
    { City: "New York", County: "New York", State: "NY" },
    { City: "Utica", County: "Oneida", State: "NY" },
    { City: "Syracuse", County: "Onondaga", State: "NY" },
    { City: "Port Jervis", County: "Orange", State: "NY" },
    { City: "Astoria", County: "Queens", State: "NY" },
    { City: "Long Island City", County: "Queens", State: "NY" },
    { City: "Troy", County: "Rensselaer", State: "NY" },
    { City: "Staten Island", County: "Richmond", State: "NY" },
    { City: "Bohemia", County: "Suffolk", State: "NY" },
    { City: "Coram", County: "Suffolk", State: "NY" },
    { City: "Deer Park", County: "Suffolk", State: "NY" },
    { City: "Middle Island", County: "Suffolk", State: "NY" },
    { City: "Ronkonkoma", County: "Suffolk", State: "NY" },
    { City: "Katonah", County: "Westchester", State: "NY" },
    { City: "Mount Vernon", County: "Westchester", State: "NY" },
    { City: "Pelham", County: "Westchester", State: "NY" },
    { City: "Yonkers", County: "Westchester", State: "NY" },
    { City: "Ashland", County: "Ashland", State: "OH" },
    { City: "Hamilton", County: "Butler", State: "OH" },
    { City: "Bucyrus", County: "Crawford", State: "OH" },
    { City: "Beachwood", County: "Cuyahoga", State: "OH" },
    { City: "Brook Park", County: "Cuyahoga", State: "OH" },
    { City: "Cleveland", County: "Cuyahoga", State: "OH" },
    { City: "Strongsville", County: "Cuyahoga", State: "OH" },
    { City: "Columbus", County: "Franklin", State: "OH" },
    { City: "Chagrin Falls", County: "Geauga", State: "OH" },
    { City: "Cincinnati", County: "Hamilton", State: "OH" },
    { City: "Findlay", County: "Hancock", State: "OH" },
    { City: "Toledo", County: "Lucas", State: "OH" },
    { City: "London", County: "Madison", State: "OH" },
    { City: "Canton", County: "Stark", State: "OH" },
    { City: "Akron", County: "Summit", State: "OH" },
    { City: "Barberton", County: "Summit", State: "OH" },
    { City: "Bowling Green", County: "Wood", State: "OH" },
    { City: "Perrysburg", County: "Wood", State: "OH" },
    { City: "Tulsa", County: "Tulsa", State: "OK" },
    { City: "Prineville", County: "Crook", State: "OR" },
    { City: "Eugene", County: "Lane", State: "OR" },
    { City: "Salem", County: "Marion", State: "OR" },
    { City: "Portland", County: "Multnomah", State: "OR" },
    { City: "Beaverton", County: "Washington", State: "OR" },
    { City: "Portland", County: "Washington", State: "OR" },
    { City: "Richboro", County: "Bucks", State: "PA" },
    { City: "Southampton", County: "Bucks", State: "PA" },
    { City: "Coatesville", County: "Chester", State: "PA" },
    { City: "Harrisburg", County: "Dauphin", State: "PA" },
    { City: "Aston", County: "Delaware", State: "PA" },
    { City: "Wayne", County: "Delaware", State: "PA" },
    { City: "Erie", County: "Erie", State: "PA" },
    { City: "Clarks Summit", County: "Lackawanna", State: "PA" },
    { City: "Old Forge", County: "Lackawanna", State: "PA" },
    { City: "Scranton", County: "Lackawanna", State: "PA" },
    { City: "Denver", County: "Lancaster", State: "PA" },
    { City: "Lancaster", County: "Lancaster", State: "PA" },
    { City: "Hazleton", County: "Luzerne", State: "PA" },
    { City: "Hatfield", County: "Montgomery", State: "PA" },
    { City: "Huntingdon Valley", County: "Montgomery", State: "PA" },
    { City: "Jenkintown", County: "Montgomery", State: "PA" },
    { City: "King of Prussia", County: "Montgomery", State: "PA" },
    { City: "Kulpsville", County: "Montgomery", State: "PA" },
    { City: "Philadelphia", County: "Philadelphia", State: "PA" },
    { City: "York", County: "York", State: "PA" },
    { City: "Johnston", County: "Providence", State: "RI" },
    { City: "Providence", County: "Providence", State: "RI" },
    { City: "Columbia", County: "Richland", State: "SC" },
    { City: "Spartanburg", County: "Spartanburg", State: "SC" },
    { City: "Sioux Falls", County: "Minnehaha", State: "SD" },
    { City: "Moss", County: "Clay", State: "TN" },
    { City: "Tullahoma", County: "Coffee", State: "TN" },
    { City: "Nashville", County: "Davidson", State: "TN" },
    { City: "Memphis", County: "Shelby", State: "TN" },
    { City: "Mc Minnville", County: "Warren", State: "TN" },
    { City: "San Antonio", County: "Bexar", State: "TX" },
    { City: "College Station", County: "Brazos", State: "TX" },
    { City: "Plano", County: "Collin", State: "TX" },
    { City: "Dallas", County: "Dallas", State: "TX" },
    { City: "Irving", County: "Dallas", State: "TX" },
    { City: "Mesquite", County: "Dallas", State: "TX" },
    { City: "El Paso", County: "El Paso", State: "TX" },
    { City: "Kerrville", County: "Kerr", State: "TX" },
    { City: "Waco", County: "McLennan", State: "TX" },
    { City: "Conroe", County: "Montgomery", State: "TX" },
    { City: "Amarillo", County: "Randall", State: "TX" },
    { City: "Arlington", County: "Tarrant", State: "TX" },
    { City: "Euless", County: "Tarrant", State: "TX" },
    { City: "Fort Worth", County: "Tarrant", State: "TX" },
    { City: "Kennedale", County: "Tarrant", State: "TX" },
    { City: "Abilene", County: "Taylor", State: "TX" },
    { City: "Austin", County: "Travis", State: "TX" },
    { City: "Laredo", County: "Webb", State: "TX" },
    { City: "Wichita Falls", County: "Wichita", State: "TX" },
    { City: "Round Rock", County: "Williamson", State: "TX" },
    { City: "Salt Lake City", County: "Salt Lake", State: "UT" },
    { City: "Annandale", County: "Fairfax", State: "VA" },
    { City: "Mc Lean", County: "Fairfax", State: "VA" },
    { City: "Fairfax", County: "Fairfax City", State: "VA" },
    { City: "Newport News", County: "Newport News City", State: "VA" },
    { City: "Richmond", County: "Richmond City", State: "VA" },
    { City: "Richland", County: "Benton", State: "WA" },
    { City: "Kent", County: "King", State: "WA" },
    { City: "Seattle", County: "King", State: "WA" },
    { City: "Vashon", County: "King", State: "WA" },
    { City: "Tacoma", County: "Pierce", State: "WA" },
    { City: "Bothell", County: "Snohomish", State: "WA" },
    { City: "Green Bay", County: "Brown", State: "WI" },
    { City: "Madison", County: "Dane", State: "WI" },
    { City: "Milwaukee", County: "Milwaukee", State: "WI" },
    { City: "Stevens Point", County: "Portage", State: "WI" },
    { City: "Beloit", County: "Rock", State: "WI" },
    { City: "Riverton", County: "Fremont", State: "WY" },
    { City: "Cheyenne", County: "Laramie", State: "WY" },
    { City: "Rock Springs", County: "Sweetwater", State: "WY" }
];